name: Sync to Gitee

on:
  push:
    branches: [ main ]

jobs:
  push-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史

      - name: Push to Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          # 注意：这里的用户名是登录名 wjx325870，不是仓库路径的 wssrwjjd
          git remote add gitee https://wjx325870:${GITEE_TOKEN}@gitee.com/wssrwjjd/KDENGINE.git
          git push -f gitee main
